image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - name: Shopware 5
    env:
      DB_USER: root
      DB_PASSWORD: gitpod
      DB_HOST: 0.0.0.0
      DB_NAME: shopware
      DB_PORT: 3306
      SW_HOST: $(gp url)
      SW_BASE_PATH: ""
    command: |
        cd $GITPOD_REPO_ROOT;
        git clone https://github.com/shopware/shopware.git --depth=1
        cd shopware;
        ls -lart

ports:
  - port: 3306
    visibility: private
    name: mysql
  - port: 80
    visibility: public
    onOpen: open-browser
    name: apache
