image:
  file: .gitpod.Dockerfile
  context: apache
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d
      docker-compose exec mysql mysqladmin ping mysqladmin ping -h 0.0.0.0 --password=gitpod
      gp sync-done db
  - name: Shopware 5
    init: gp sync-await db
    env:
      DB_USER: root
      DB_PASSWORD: gitpod
      DB_HOST: 0.0.0.0
      DB_NAME: shopware
      DB_PORT: 3306
      SW_BASE_PATH: ""
    command: |
      cd $GITPOD_REPO_ROOT;
      git clone https://github.com/shopware/shopware.git --depth=1
      cd shopware;
      export SW_HOST=$HOSTNAME
      env | grep -v GITPOD | grep -v LS_COLORS | grep -v THEIA | grep -v GP_
      make init

ports:
  - port: 3306
    visibility: private
    name: mysql
    onOpen: ignore

  - port: 8001
    name: apache
    onOpen: open-preview
