image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - name: Shopware 5
    command: |
        cd $GITPOD_REPO_ROOT;
        git clone https://github.com/shopware/shopware.git --depth=1
        cd shopware;
        ls -lart

ports:
  - port: 3306
    onOpen: ignore
