services:
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
#    volumes:
#     - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitpod
      - MYSQL_PASSWORD=gitpod
      - MYSQL_DATABASE=shopware
    networks:
      - shopware
networks:
  shopware:
    driver: bridge
